# taking python as base image...
FROM python:3.11-slim

# setting work directory...
WORKDIR /app

# installing syste, libraries...
RUN apt-get update && apt-get install -y \
    libpq-dev && apt-get clean

# installing requirements.txt...
COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt --verbose

# copying the project in app...
COPY . /app/

# setting up the port...
EXPOSE 8000

# command to run...
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]